let testData = [
  {
    preview: "Картинка",
    firstName: "Егор",
    lastName: "Пупкин",
    birth: "20.08.1992",
    age: "38",
    vacancy: "Разработчик",
    remote: false,
    id: 1,
    url:
      "https://3dnews.ru/assets/external/illustrations/2017/04/05/950272/aidl-1.jpg",
    city: "Spb",
    street: "White Ocean",
    home: "228",
    room: "1488",
    address: "Город Spb ул. White Ocean д. 228 кв. 1488",
  },
  {
    preview: "Картинка",
    firstName: "Василий",
    lastName: "Жмыхов",
    birth: "20.08.1992",
    age: "38",
    vacancy: "Разработчик",
    remote: false,
    id: 2,
    url: "https://photo-ideal.ru/upload/iblock/6b3/foto_na_rezyume_37.jpg",
    city: "Spb",
    street: "White Ocean",
    home: "228",
    room: "1488",
    address: `Город Spb ул. White Ocean д. 228 кв. 1488`,
  },
  {
    preview: "Картинка",
    firstName: "Алексей",
    lastName: "Щербаков",
    birth: "20.08.1992",
    age: "38",
    vacancy: "Разработчик",
    remote: false,
    id: 3,
    url: "https://photo-ideal.ru/upload/iblock/557/foto_na_rezyume_3.jpg",
    city: "Spb",
    street: "White Ocean",
    home: "228",
    room: "1488",
    address: `Город Spb ул. White Ocean д. 228 кв. 1488`,
  },
];

export default testData;
